### ISSUE TITLE
Champs additionnels requête/réponse DF

### ISSUE THREAD

**Issue by magemax** [leximpact/leximpact-server#36]
Plusieurs questions :  

**Pour la requête :** 

Quels paramètres fait-on changer ? 

possiblement : 
    - montant min par habitant nouveau/ancien (64.46)
    - montant max par habitant nouveau (128.93)
    - Taux de Potentiel fiscal à partir duquel on écrète (75% du PF moyen)
    - Plafond de l'écrètement en pourcentage des recettes réelles de fonctionnement : 1%

On aurait donc la requête 

    "dotations": {
        "communes":{
            "df":{
                "montantMinParHab": 64.46,
                "montantMaxParHab": 128.93,
                "ecretement":{
                    "potentielFiscalLimite": 0.75,
                    "pourcentageRecettesMax": 0.01 
                }
            }
        }
    }

NB : les montants par habitant n'auront pas d'impact si nous ne parvenons pas à obtenir l'évolution de la population DGF d'ici 2021.

**Pour la réponse,** pour l'instant on aurait simplement les champs
- dotationParHabitant (cas type et strate)
- partDotationTotale (strate)

Pour les autres : 
- Les champs partPopTotale et potentielFinancierMoyenParHabitant (voire habitants) : on se rend compte qu'on l'envoie pour chaque dotation dans les strates, peut être pourrait-on le mettre ailleurs. En attendant, lequel utilises-tu @LoicPoullain  (on imagine le DSR). A t on besoin d'inclure ces champs pour la DF?  Pourrait on envisager de les supprimer aussi pour la DSU (ça fait gagner un chouia de temps de calcul/bande passante)
- Eligibilité : Le concept n'existe pas dans le monde de la DF.  Toutes les communes ne la touchent pas (environ 1000 communes ne recoivent rien), donc on peut faire figurer une info du genre (et même l'appeler "eligibilité"), mais il faudra au moins spécifier en tooltip et est ce bien ce qu'on veut ?
- Du coup on n'a rien dans le baseToAmendement de la DF ? (cf paragraphe suivant)

Champs spécifiques à la DF : La DF a des spécificités donc on pourrait rajouter d'autres infos suite à ce dev, en fonction de ce qui peut intéresser : 
-  L'écrètement c'est important, et pour le coup, y a une éligibilité à l'écrètement. On pourrait faire figurer ça (environ 40% des communes ne sont pas écrétées en 2020)
- La DF est caractérisée par son montant, mais aussi par son rythme d'écrètement (absolu, ou relatif par rapport à la population). On pourrait imaginer un truc du genre "La commune de XX touchait 30€ de DF par habitant l'an dernier et a perdu 5% de sa DF par écrètement alors que la moyenne de sa strate a perdu 3% de sa DF par écrètement".   Ou (ce qui ne serait pas la même chose, cf exemple de Paris) : "La commune de XX touchait 30€ de DF par habitant l'an dernier et a perdu 1.5€ par habitant par écrètement alors que la moyenne de sa strate a perdu 3€ par habitant par écrètement". Ce genre de datapoint peut concerner les cas types comme les strates.
- Des trucs sur la répartition de l'écrètement du coup ? Genre estce que y a des strates qui les payent plus que d'autres (ça équivaudrait à filer en gros les infos qu'on file, mais sur une dotation qui serait négative : l'écrètement)

On rajouterait donc à la réponse (au niveau du scenario) les champs suivants : 

    "amendement": {
        "communes": {
            "df": {
                "communes": [
                    {
                        "code": "76384",
                        "dotationParHab": 7.010937154543445
                    }
                ]
            },
            "strates": [
                    {
                        "dotationMoyenneParHab": 48.12175873540341,
                        "habitants": 0,
                        "partDotationTotale": 0.12566914176037117
                    }
            ]
        }

**Comment by LoicPoullain** [comment]
> On aurait donc la requête

La forme de la spec est très bien.

Sur le choix des paramètres, il me semble bon (c'est d'ailleurs ceux qu'on faisait figurer sur le front en cachés `?df`). Sur les montants par habitant, il faut peut-être faire une hypothèse sur les variations futures du nombre d'habitants de chaque commune, sinon les deux paramètres ne serviront à rien. Pourquoi ne pas reprendre les variations de 2020 par rapport à 2019 ?


> **Pour la réponse,** pour l'instant on aurait simplement les champs
> 
> * dotationParHabitant (cas type et strate)
> * partDotationTotale (strate)

La même chose en tête (cf https://trello.com/c/0Qg1W2wO/419-impl%C3%A9menter-df). Attention toutefois sur le nommage: `dotationParHab` pour les cas types et `dotationMoyenneParHab` pour les states.

**Comment by LoicPoullain** [comment]
> * Les champs partPopTotale et potentielFinancierMoyenParHabitant (voire habitants) : on se rend compte qu'on l'envoie pour chaque dotation dans les strates, peut être pourrait-on le mettre ailleurs. En attendant, lequel utilises-tu @LoicPoullain  (on imagine le DSR). A t on besoin d'inclure ces champs pour la DF?  Pourrait on envisager de les supprimer aussi pour la DSU (ça fait gagner un chouia de temps de calcul/bande passante)

Pour l'instant, ces valeurs sont codées _en dur_ sur le front (ce qui n'est pas l'idéal en cas de changement de données). Pour éviter les duplicats, on pourrait opter pour cette spec :
```typescript
interface RequesBody {
  amendement: {
    communes: {
      common: {
        strates: { partPopTotale: number; potentielFinancierMoyenParHab: number; }[]
      }
      dsr: { ... }
      dsu: { ... }
      df: { ... }
    }
  }
}
```

**Comment by LoicPoullain** [comment]
> * Eligibilité : Le concept n'existe pas dans le monde de la DF.  Toutes les communes ne la touchent pas (environ 1000 communes ne recoivent rien), donc on peut faire figurer une info du genre (et même l'appeler "eligibilité"), mais il faudra au moins spécifier en tooltip et est ce bien ce qu'on veut ?

Je pense que le plus simple serait de ne rien mettre (un `-` dans la colonne "éligibles" par exemple)

**Comment by LoicPoullain** [comment]
> * Du coup on n'a rien dans le baseToAmendement de la DF ?

Oui, rien dans `baseToAmendement` et `baseToPlf`

**Comment by LoicPoullain** [comment]
> * L'écrètement c'est important, et pour le coup, y a une éligibilité à l'écrètement. On pourrait faire figurer ça (environ 40% des communes ne sont pas écrétées en 2020)

Peut-être rajouter un champs `ecrete: boolean;` aux communes types (réponse).

**Comment by LoicPoullain** [comment]
> * La DF est caractérisée par son montant, mais aussi par son rythme d'écrètement (absolu, ou relatif par rapport à la population). On pourrait imaginer un truc du genre "La commune de XX touchait 30€ de DF par habitant l'an dernier et a perdu 5% de sa DF par écrètement alors que la moyenne de sa strate a perdu 3% de sa DF par écrètement".   Ou (ce qui ne serait pas la même chose, cf exemple de Paris) : "La commune de XX touchait 30€ de DF par habitant l'an dernier et a perdu 1.5€ par habitant par écrètement alors que la moyenne de sa strate a perdu 3€ par habitant par écrètement". Ce genre de datapoint peut concerner les cas types comme les strates.

Pas trop d'envie là-dessus. Moins prioritaire peut-être ?

**Comment by LoicPoullain** [comment]
> * Des trucs sur la répartition de l'écrètement du coup ? Genre estce que y a des strates qui les payent plus que d'autres (ça équivaudrait à filer en gros les infos qu'on file, mais sur une dotation qui serait négative : l'écrètement)

Est-ce que cela ne se voit pas directement avec la moyenne de la DF par strate ? Dis-moi si je me trompe, mais j'ai l'impression que l'écrêtement est la grosse variation de la DF et que donc "baisse DF = écrêtement important".

**Comment by DorineLam** [comment]
Hello ! Merci @magemax, c'était très clair, voici donc mes réponses : 

Côté impact sur les communes, je ne me vois pas ajouter encore un paramètre visible en permanence, c'est trop lourd, et le plus important c'est la tendance pour la commune. 
Par contre, clarifier le mécanisme dans un tooltip me paraît être une bonne alternative :
<img width="959" alt="Capture d’écran 2020-09-21 à 13 52 41" src="https://user-images.githubusercontent.com/46896006/93763457-c2bc8600-fc11-11ea-8afe-62666623eca1.png">

Côté impact par strates démographiques, c'est effectivement intéressant de pouvoir donner la proportion des communes touchées par l'écrêtement. J'ai fait une maquette, après, au niveau de l'emplacement des colonnes, je me demande si la colonne "proportion des communes écrêtées par la DF" n'intervient pas à la toute fin du tableau.
<img width="975" alt="Capture d’écran 2020-09-21 à 13 40 52" src="https://user-images.githubusercontent.com/46896006/93763480-d0720b80-fc11-11ea-841d-710b57a74e63.png">

**Comment by sandcha** [comment]
Fixed by #37 and #39 🙌
